version: '3.0'

services: 
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: pet-project
    ports: 
      - 5432:5432
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    container_name: pet-project

volumes:
  postgres:
